version: '3'

services:
 web:
  build: .
  working_dir: /code/HouseholdLedger
  command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000 && python3 manage.py createsuper"
  volumes:
   - $PWD:/code/HouseholdLedger
  tty: true
  ports:
   - "8000:8000"
  depends_on:
   - db

 db:
  image: postgres:10
  # restart: always
  ports: 
   - "5432:5432"
  environment:
   POSTGRES_PASSWORD: password
   POSTGRES_USER: django
   # MYSQL_USER: root
   # MYSQL_PASSWORD: password
  tty: true
