# Generated by Django 2.0.4 on 2018-07-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_type2',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
