# Generated by Django 2.0.4 on 2018-07-21 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_budget_budget_type2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='budget_type2',
        ),
    ]
