# Generated by Django 2.0.4 on 2018-07-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_remove_budget_budget_type2'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='credit_type',
            field=models.SmallIntegerField(),
        ),
        migrations.AddField(
            model_name='transaction',
            name='debit_type',
            field=models.SmallIntegerField(),
        ),
    ]
