# Generated by Django 2.0.4 on 2018-08-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20180722_0809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
