# Generated by Django 2.0.4 on 2018-08-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField('Budget', 'amount', 'cost_amount'),

    ]
