# Generated by Django 2.0.4 on 2018-08-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20180812_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_name',
            field=models.CharField( max_length=100),
        ),
    ]
