# Generated by Django 2.0.4 on 2018-08-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budget_budget_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
