version: '3'

services:
 web:
  build: .
  working_dir: /code/HouseholdLedger
#  command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000 && python3 manage.py createsuper"
  volumes:
   - $PWD:/code/HouseholdLedger
   - $PWD/log/django:/var/log/django
  tty: true
  ports:
   - "8000:8000"
  depends_on:
   - db
  links:
   - db:db
  command: ["./wait-for-db.sh"]
 db:
  image: postgres:10
  # restart: always
  ports: 
   - "5432:5432"
  environment:
   POSTGRES_PASSWORD: password
   POSTGRES_USER: django
  tty: true
  volumes:
   - $PWD/postgres/data:/var/lib/postgresql/data
   - $PWD/postgres/log:/var/log/postgresql
   - $PWD/postgres/etc:/etc/postgresql
